name: DeepX CI

run-name: Build Docker container and perform unit testing

on: [push, workflow_dispatch]

jobs:
  build-library:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: deepx-inc
          password: ${{ github.token }}

      - name: Build the Docker container
        run: docker build --build-arg BASE_IMAGE=ghcr.io/deepx-inc/base_images --build-arg TAG=foxy -t deepx-gz-rendering .

      - name: Commit the Docker container
        run: |
          docker run --name deepx-gz-rendering-container \
          -v $GITHUB_WORKSPACE:/root/gazebo \
          --entrypoint bash \
          -w /root/gazebo deepx-gz-rendering \
          -c 'cd /root/gazebo/gz-rendering/; mkdir build; cd build; cmake ..; make install; echo "$(pwd)"'
          docker commit deepx-gz-rendering-container deepx-gz-rendering-image

      - name: Run tests
        run: |
          docker run --name deepx-gz-rendering-image \
          -v $GITHUB_WORKSPACE:/root/gazebo \
          --entrypoint bash \
          -w /root/gazebo \
          deepx-gz-rendering-image \
          -c 'cd /root/gazebo/gz-rendering/build && ctest'
