name: DeepX CI

run-name: Build Docker container and perform unit testing

on: 
  push:
    branches: [ign-rendering6]
  pull_request:
    branches: [ign-rendering6]
  workflow_dispatch:

jobs:
  build-library:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: deepx-inc
          password: ${{ github.token }}

      - name: Build and commit the Docker container
        run: |
          docker build -t deepx-gz-rendering .
      
      - name: Run tests
        run: |
          docker run deepx-gz-rendering:latest bash \
          -c 'cd /root/gazebo/gz-rendering/build; \
          cmake ..; \
          cmake --build . --target install -j; \
          ctest;'