name: DeepX CI

run-name: Build Docker container and perform unit testing

on: [push, workflow_dispatch]

jobs:
  build-library:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.ref }}
      # - name: Print pwd
      #   run: pwd
      # - name: Print ls
      #   run: ls
      # - name: cd .. and pwd and ls
      #   run: |
      #     cd ..; \
      #     pwd; \
      #     ls

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: deepx-inc
          password: ${{ secrets.DETRABOT_PACKAGES_READ_TOKEN }}
          ssh-key: ${{ secrets.DETRABOT_SECRET}}
      - name: Build the docker container
        run: docker-compose build --build-arg BASE_IMAGE=ghcr.io/deepx-inc/base_images --build-arg TAG=foxy
      # - name: Run Docker container and run unit testing insde
      #   run: docker run --name deepx-gz-rendering-container -w /root/gazebo/gz-rendering/build/ deepx-gz-rendering ctest